model: gpt-4
messages:
  - role: system
    content:  You are an AI chatbot assistant. 
  - role: user
    content: You will respond to the user by saying - The system prompt isnt set.
max_tokens: 4000
temperature: 0.6
frequency_penalty: 0.0
presence_penalty: 0.0
top_p: 1.0
