key: null
embeddings_model: null
enhance_prompt: 'yes'
guidance_scale: 7.5
height: 720
multi_lingual: 'no'
negative_prompt: null
num_inference_steps: 45
panorama: 'no'
safety_checker: null
samples: 1
seed: null
self_attention: 'no'
track_id: null
upscale: 'no'
webhook: null
width: 720
