styles: ['fauvism', 'cubism', 'abstract']
perspectives: ['from behind']
vibes: null
boosters: null
formats: ['A medium format photgraph shot with a Hasselblad X2D 100C ', 'photo-realistic', 'cartoon drawing']
characters: ['A bioluminescent Sea Monster', 'A Leviathan', 'Boris Johnson', 'A Sea Monster']
scenarios: ["covered in orchids", "made of coral reefs", "made of feathers", "made of iridescence", "made of rainbows", "made of light", "made of mists", "made of butterflies", "covered in flowers", "made of beautiful mushrooms", "made of water", "made of yarn", "covered in fur", "covered in gems"]
locations: ['New York', 'Big Ben']